version: 0.0
os: windows
files:
  - source: \refdef.web
    destination: C:\inetpub\wwwroot\refdef.web
    overwrite: yes
hooks:
  AfterInstall:
    - location: scripts/install.ps1
      timeout: 180
  ApplicationStart:
    - location: scripts/applicationStart.ps1
      timeout: 180
